virt: lxd

language: c

git:
     depth: 1


before_install:
     - pyenv global 3.7.1
     - pip install -U pip
     - pip install awscli
     - mkdir -p ~/$TRAVIS_BUILD_NUMBER
     - aws s3 sync s3://elisa.kernel.test/$TRAVIS_BUILD_NUMBER ~/$TRAVIS_BUILD_NUMBER

jobs:
  include:
    - stage: setup files
      script: echo one | tee > ~/$TRAVIS_BUILD_NUMBER/smatch_warns.txt
    - stage: setup files
      script: echo two | tee > ~/$TRAVIS_BUILD_NUMBER/clang_out
    - stage: use shared files
      script:
        - cat ~/$TRAVIS_BUILD_NUMBER/*
      after_success:
        - aws s3 rm --recursive s3://elisa.kernel.test/$TRAVIS_BUILD_NUMBER

after_success:
  - aws s3 sync ~/$TRAVIS_BUILD_NUMBER s3://elisa.kernel.test/$TRAVIS_BUILD_NUMBER
