virt: lxd

language: c

git:
     depth: 1

before_install:
     - pyenv global 3.7.1
     - pip install -U pip
     - pip install awscli
     - mkdir -p ~/backup/cache
     - aws s3 sync s3://elisa.kernel.test/backup ~/backup

services:
     - docker

jobs:
  include:
    - stage: build
      before_install:
       - docker pull sudipm/clang:report
      script:
        - docker run -v "$PWD":/src --workdir /src sudipm/clang:report /bin/bash -c "./build.sh clang tinyconfig"
        - cp clang_log ~/backup/cache/.

    - stage: build
      before_install:
       - docker pull sudipm/smatch
      script:
        - cp ~/backup/backup.tar.bz2 .  || true
        - docker run -v "$PWD":/src --workdir /src sudipm/smatch /bin/bash -c "./build smatch tinyconfig"
        - cp backup.tar.bz2 ~/backup/.
        - cp smatch_warns.txt ~/backup/cache/.

    - stage: report
      before_install:
       - docker pull sudipm/clang:report
      script:
        - cp ~/backup/cache/* .  || true
        - docker run -v "$PWD":/src --workdir /src sudipm/clang:report /bin/bash -c "./build.sh report"
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GKEY
        local_dir: reports_html
        repo: sudipm-mukherjee/sudipm-mukherjee.github.io
        verbose: true
        target_branch: test
        on:
          branch: test_smatch_clang
      after_success:
        - aws s3 rm --recursive s3://elisa.kernel.test/backup/cache

after_success:
  - aws s3 sync ~/backup s3://elisa.kernel.test/backup
