virt: lxd

language: c

git:
     depth: 1

script:
     - echo "abcd" > smatch_warns.txt

addons:
     artifacts:
       paths: smatch_warns.txt
       target_paths: /log
       s3_region: "eu-west-2"
       debug: true
