virt: lxd

language: c

git:
     depth: 1

services:
     - docker

jobs:
  include:
    - stage: build
      before_install:
       - docker pull sudipm/clang:report
      script:
       - docker run -v "$PWD":/src --workdir /src sudipm/clang:report /bin/bash -c "./build.sh tinyconfig"
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GKEY
        local_dir: reports_html
        repo: sudipm-mukherjee/sudipm-mukherjee.github.io
        verbose: true
        target_branch: test
        on:
          branch: linux
    - stage: build
      before_install:
       - docker pull sudipm/smatch
      script:
       - docker run -v "$PWD":/src --workdir /src sudipm/smatch /bin/bash -c "./build_smatch.sh tinyconfig"
    - stage: report
      script: echo "all done"
