virt: lxd

language: c

git:
     depth: 1

services:
     - docker

before_install:
     - docker pull sudipm/smatch

script:
     - docker run -v "$PWD":/src --workdir /src sudipm/smatch /bin/bash -c "./build_smatch.sh defconfig"
